# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `haml-rails` gem.
# Please instead update this file by running `bin/tapioca gem haml-rails`.

# source://haml-rails//lib/haml-rails.rb#5
module Haml
  class << self
    # source://haml/5.2.2/lib/haml.rb#16
    def init_rails(*args); end
  end
end

# source://haml-rails//lib/haml-rails.rb#6
module Haml::Rails; end

# source://haml-rails//lib/haml-rails.rb#7
class Haml::Rails::Engine < ::Rails::Engine
  class << self
    # source://activesupport/6.1.7.3/lib/active_support/callbacks.rb#67
    def __callbacks; end
  end
end

# source://haml-rails//lib/haml-rails.rb#9
class Haml::Rails::Railtie < ::Rails::Railtie; end
