# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `middleware` gem.
# Please instead update this file by running `bin/tapioca gem middleware`.

# source://middleware//lib/middleware/version.rb#1
module Middleware; end

# This provides a DSL for building up a stack of middlewares.
#
# This code is based heavily off of `Rack::Builder` and
# `ActionDispatch::MiddlewareStack` in Rack and Rails, respectively.
#
# # Usage
#
# Building a middleware stack is very easy:
#
#     app = Middleware::Builder.new do
#       use A
#       use B
#     end
#
#     # Call the middleware
#     app.call(7)
#
# source://middleware//lib/middleware/builder.rb#19
class Middleware::Builder
  # Initializes the builder. An optional block can be passed which
  # will be evaluated in the context of the instance.
  #
  # Example:
  #
  #     Builder.new do
  #       use A
  #       use B
  #     end
  #
  # @option opts
  # @param opts [Hash] Options hash
  # @return [Builder] a new instance of Builder
  # @yield [] Evaluated in this instance which allows you to use methods
  #   like {#use} and such.
  #
  # source://middleware//lib/middleware/builder.rb#35
  def initialize(opts = T.unsafe(nil), &block); end

  # Runs the builder stack with the given environment.
  #
  # source://middleware//lib/middleware/builder.rb#101
  def call(env = T.unsafe(nil)); end

  # Deletes the given middleware object or index
  #
  # source://middleware//lib/middleware/builder.rb#95
  def delete(index); end

  # Returns a mergeable version of the builder. If `use` is called with
  # the return value of this method, then the stack will merge, instead
  # of being treated as a separate single middleware.
  #
  # source://middleware//lib/middleware/builder.rb#44
  def flatten; end

  # Inserts a middleware at the given index or directly before the
  # given middleware object.
  #
  # source://middleware//lib/middleware/builder.rb#68
  def insert(index, middleware, *args, &block); end

  # Inserts a middleware after the given index or middleware object.
  #
  # source://middleware//lib/middleware/builder.rb#76
  def insert_after(index, middleware, *args, &block); end

  # Inserts a middleware at the given index or directly before the
  # given middleware object.
  #
  # source://middleware//lib/middleware/builder.rb#68
  def insert_before(index, middleware, *args, &block); end

  # Replaces the given middlware object or index with the new
  # middleware.
  #
  # source://middleware//lib/middleware/builder.rb#84
  def replace(index, middleware, *args, &block); end

  # Adds a middleware class to the middleware stack. Any additional
  # args and a block, if given, are saved and passed to the initializer
  # of the middleware.
  #
  # @param middleware [Class] The middleware class
  #
  # source://middleware//lib/middleware/builder.rb#55
  def use(middleware, *args, &block); end

  protected

  # Returns the numeric index for the given middleware object.
  #
  # @param object [Object] The item to find the index for
  # @return [Integer]
  #
  # source://middleware//lib/middleware/builder.rb#111
  def index(object); end

  # Returns the current stack of middlewares. You probably won't
  # need to use this directly, and it's recommended that you don't.
  #
  # @return [Array]
  #
  # source://middleware//lib/middleware/builder.rb#123
  def stack; end

  # Converts the builder stack to a runnable action sequence.
  #
  # @return [Object] A callable object
  #
  # source://middleware//lib/middleware/builder.rb#130
  def to_app; end
end

# This is a basic runner for middleware stacks. This runner does
# the default expected behavior of running the middleware stacks
# in order, then reversing the order.
#
# source://middleware//lib/middleware/runner.rb#5
class Middleware::Runner
  # Build a new middleware runner with the given middleware
  # stack.
  #
  # Note: This class usually doesn't need to be used directly.
  # Instead, take a look at using the {Builder} class, which is
  # a much friendlier way to build up a middleware stack.
  #
  # @param stack [Array] An array of the middleware to run.
  # @return [Runner] a new instance of Runner
  #
  # source://middleware//lib/middleware/runner.rb#17
  def initialize(stack); end

  # Run the middleware stack with the given state bag.
  #
  # @param env [Object] The state to pass into as the initial
  #   environment data. This is usual a hash of some sort.
  #
  # source://middleware//lib/middleware/runner.rb#27
  def call(env); end

  protected

  # This takes a stack of middlewares and initializes them in a way
  # that each middleware properly calls the next middleware.
  #
  # source://middleware//lib/middleware/runner.rb#38
  def build_call_chain(stack); end
end

# A middleware which does nothing
#
# source://middleware//lib/middleware/runner.rb#7
Middleware::Runner::EMPTY_MIDDLEWARE = T.let(T.unsafe(nil), Proc)

# source://middleware//lib/middleware/version.rb#2
Middleware::VERSION = T.let(T.unsafe(nil), String)
