# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actor.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("actor.proto", :syntax => :proto3) do
    add_message "protos.User" do
      optional :identity, :string, 1
      optional :role, :enum, 2, "protos.Role"
    end
    add_enum "protos.Role" do
      value :ROLE_UNKNOWN, 0
      value :ROLE_SCIENTIST, 1
      value :ROLE_BUILDER, 2
    end
  end
end

module Protos
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.User").msgclass
  Role = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.Role").enummodule
end
