# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cage.proto

require 'google/protobuf'

require 'dinosaur_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("cage.proto", :syntax => :proto3) do
    add_message "protos.Cage" do
      optional :name, :string, 1
      optional :status, :enum, 2, "protos.Status"
      optional :population, :int32, 3
      optional :capacity, :int32, 4
    end
    add_message "protos.CageInhabitants" do
      optional :name, :string, 1
      optional :status, :enum, 2, "protos.Status"
      repeated :inhabitants, :message, 5, "protos.Dinosaur"
    end
    add_enum "protos.Status" do
      value :STATUS_UNKNOWN, 0
      value :STATUS_ACTIVE, 1
      value :STATUS_DOWN, 2
    end
  end
end

module Protos
  Cage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.Cage").msgclass
  CageInhabitants = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.CageInhabitants").msgclass
  Status = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("protos.Status").enummodule
end
